### ISSUE TITLE
Remove deleted collections in Solr

### ISSUE THREAD

**Issue by swandog30** [Minitex/mdl_search#124]
Collections that are deleted in CDM still appear in Blacklight.  For example, `mdltest_nancy` still appears:

https://collection.mndigital.org/?f%5Bcollection_name_ssi%5D%5B%5D=mdltest_nancy

**Comment by DanOlson** [comment]
@swandog30 - I have a [PR in the CDMBL repo](https://github.com/Minitex/cdmbl/pull/2) that will address some issues with an existing Sidekiq job we can run to take care of this issue. Once it's merged, I'll bump the gem's version, use that repo as the gem source for CDMBL, and make an additional PR to mdl_search with those changes.

**Comment by swandog30** [comment]
@DanOlson I've got that merged in so bump away and I'll watch for the PR in mdl_search

**Comment by swandog30** [comment]
This looks good and is working.  I'll close this and create a new issue for deletion scoping.
