### ISSUE TITLE
Migrate default thumbnail storage away from ULibraries AWS

### ISSUE THREAD

**Issue by swandog30** [Minitex/mdl_search#126]
Thumbnail placeholder images are served up from an S3 bucket in the ULibraries AWS account.  Let's migrate this to /public or our AWS account.

The CDN URLs are hard coded like https://d1kue88aredzk1.cloudfront.net:

https://github.com/Minitex/mdl_search/search?q=d1kue88aredzk1

These files are getting to cloudfront.net by way of an S3 bucket called mdl-assets which we don't have access to. These  could just as well be served right out of public/ instead.  The full bucket contents:

$ aws --profile=dls s3 ls s3://mdl-assets | awk '{print "https://mdl-assets.s3.amazonaws.com/"$4}'
https://mdl-assets.s3.amazonaws.com/audio-1.png
https://mdl-assets.s3.amazonaws.com/audio-2.png
https://mdl-assets.s3.amazonaws.com/audio-3.png
https://mdl-assets.s3.amazonaws.com/audio.jpg
https://mdl-assets.s3.amazonaws.com/facebook-128-black.png
https://mdl-assets.s3.amazonaws.com/homepage-collection-new.jpg
https://mdl-assets.s3.amazonaws.com/homepage-format.jpg
https://mdl-assets.s3.amazonaws.com/homepage-topic-new.jpg
https://mdl-assets.s3.amazonaws.com/reflections-pdf-icon.png
https://mdl-assets.s3.amazonaws.com/stpaul.pdf
https://mdl-assets.s3.amazonaws.com/trainwreck.png
https://mdl-assets.s3.amazonaws.com/video-1.png
https://mdl-assets.s3.amazonaws.com/video.jpg

@mberkowski found this and supplied the detail

**Comment by DanOlson** [comment]
@swandog30 the PR for this is deployed to QA2 currently. There were only four of these files that we were using, default images for audio, video, and PDF documents, and the trainwreck 404 image. I didn't bother moving the others in to the repo, but let me know if you think we need to.
