### ISSUE TITLE
"Search within this item" 500 errors in production

### ISSUE THREAD

**Issue by mberkowski** [Minitex/mdl_search#201]
The "search within this item" feature is producing 500 errors for both the autocomplete and search endpoints. For example:

* https://collection.mndigital.org/iiif/p16022coll64:37628/autocomplete?q=bulbs
* https://collection.mndigital.org/iiif/p16022coll64:37628/search?q=bulbs

This may or may not be the source, but a place I can think of to look in this is at `hl.method=unified` when doing Solr search term highlighting in `app/services/iiif_search_service.rb` & `app/services/iiif_search_autocomplete_service.rb`. We have seen some odd behaviors with the unified highlighter in some contexts and have had to fall back on `hl.method=original`. Using `original` produced slightly shorter contextual text around the highlighted result but works the same. Mostly it meant updating test fixtures.

When we've encountered this in UMedia, the logs had errors like
```
"error":{
    "msg":"field 'title' was indexed without offsets, cannot highlight",
    "trace":"java.lang.IllegalArgumentException: field 'title' was indexed without offsets, cannot highlight\n\tat org.apache.lucene.search.uhighlight.FieldHighlighter.highlightOffsetsEnums(FieldHighlighter.java:149)\n\tat org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:80)
```

See also:
* https://github.com/UMNLibraries/umedia/issues/64
* https://github.com/UMNLibraries/umedia/pull/66/files

**Comment by DanOlson** [comment]
The problem was that the mdl-iiif-search Solr core had disappeared. I recreated it and everything is back up and running. Not sure what happened to it, but I will keep an eye on it
