### ISSUE TITLE
back button errors when viewing an item from a search that has more than 25 items on a page

### ISSUE THREAD

**Issue by swandog30** [Minitex/mdl_search#290]
When clicking into an item in a search result that contains more than the default 25 items per page, and then clicking the back button from there, you get the generic rails error screen.

Steps to reproduce:
1. Go to https://collection.mndigital.org/?f%5Bcollection_name_ssi%5D%5B%5D=Minnesota+Department+of+Transportation
2. Change the number of items per page to 50 or 100
3. Click into any object
4. Click the back button from that object.

https://minitex.teamwork.com/app/tasks/31631624

**Comment by DanOlson** [comment]
@swandog30 I'm not able to reproduce this using the above instructions. I've tried FireFox and Chrome. Is this still happening?

**Comment by swandog30** [comment]
@DanOlson It's still happening but seems intermittent...  try these steps:

1. Open an incognito window in Chrome, browse to mndigital.org.
2. Click Browse by Contributor.
3. Click American Craft Council.
4. Change to 100 items per page.
5. Click into the second item in the result set.
6. Click the back button.

**Comment by DanOlson** [comment]
Got it! That was helpful, thanks!
